# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Describely"
handle = "describely"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://describely.app/auth/callback",
  "https://describely.app/auth/shopify/callback",
  "https://describely.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
