# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "980b9fdec91d29abb22733c8479d7898"
name = "InkBot"
application_url = "https://inkbot.app/app"
embedded = true

[webhooks]
api_version = "2025-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://inkbot.app/webhooks"
  customer_data_request_url = "https://inkbot.app/webhooks"
  shop_deletion_url = "https://inkbot.app/webhooks"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://inkbot.app/auth/callback",
  "https://inkbot.app/auth/shopify/callback",
  "https://inkbot.app/api/auth/callback"
]
